/* automatically generated by rust-bindgen */

pub type size_t = ::std::os::raw::c_ulong;
#[repr(C)]
#[derive(Copy, Clone)]
pub struct Struct_GNUNET_CRYPTO_EddsaPublicKey {
    pub q_y: [u8; 32],
}
impl ::std::default::Default for Struct_GNUNET_CRYPTO_EddsaPublicKey {
    fn default() -> Self {
        Self { q_y: [0; 32] }
    }
}

pub const GNUNET_DNSPARSER_MAX_NAME_LENGTH: u16 = 253;
