/* automatically generated by rust-bindgen */

#[repr(C)]
#[derive(Copy, Clone)]
pub struct EddsaPublicKey {
    pub q_y: [u8; 32],
}
impl ::std::default::Default for EddsaPublicKey {
    fn default() -> Self {
        Self { q_y: [0; 32] }
    }
}

pub const GNUNET_DNSPARSER_MAX_NAME_LENGTH: u16 = 253;
